### ISSUE TITLE
Website deployment role

### ISSUE THREAD

**Issue by anadahz** [PrivacyLx/privacylx-issue-tracker#16]
This issue is about the creating a website deployment role.

**Comment by francisco-core** [comment]
now working on this

**Comment by francisco-core** [comment]
Pull request in progress here: https://github.com/PrivacyLx/devops/pull/2

@anadahz you had already done some progress in a deployment role for a hugo website with caddy but there were a few problems:
 - the hugo docker on the latest version is not able to compile to html (possibly something we need to change in the website - there were some messages about `.URL` going deprecated) But this is ok, as long as we keep using `hugo 0.52`
 - caddy no longer provides the builds repository (discussion [here](https://caddy.community/t/please-bring-back-github-com-caddyserver-builds/5552)) on which your deployment role relied. So I made it install caddy from binary on the deployment machine instead of on a docker container

But it seems to work mostly fine

**Comment by anadahz** [comment]
Thanks for working on this.

> caddy no longer provides the builds repository (discussion here) on which your deployment role relied. So I made it install caddy from binary on the deployment machine instead of on a docker container

I have chosen to build caddy from source rather than using the binary in order to get rid of the telemetry function. Do you know if the binary is without the telemetry function (not only disabled)?

**Comment by francisco-core** [comment]
> Thanks for working on this.

no problem :)

Yes, I am aware. The binary by default disables the telemetry through the environment variable. On the forums it gives the impression that it is mostly disabled but not as disabled as through doing it in the source like before.

> I have chosen to build caddy from source rather than using the binary in order to get rid of the telemetry function. Do you know if the binary is without the telemetry function (not only disabled)?

What should we do about this. Is it worth it to put in the effort to revive the docker image?

Activado ter, jun 25, 2019 às 19:08, anadahz <notifications@github.com> escreveu:

**Comment by anadahz** [comment]
> What should we do about this. Is it worth it to put in the effort to revive the docker image?

What was the issue exactly?
I see that Caddy's builder [Dockerfile](https://github.com/abiosoft/caddy-docker/blob/master/Dockerfile-no-stats) is still active (was updated 2 days ago).

**Comment by francisco-core** [comment]
> What was the issue exactly?
> I see that Caddy's builder [Dockerfile](https://github.com/abiosoft/caddy-docker/blob/master/Dockerfile-no-stats) is still active (was updated 2 days ago).

It was just outdated. So we need to remake it with the docker image compiling it from source and removing the telemetry at compile time.
