### ISSUE TITLE
Privacylx.org server full

### ISSUE THREAD

**Issue by francisco-core** [PrivacyLx/privacylx-issue-tracker#28]
issue for https://github.com/PrivacyLx/devops

result of `df -h`:
```bash
Filesystem      Size  Used Avail Use% Mounted on
udev             10M     0   10M   0% /dev
tmpfs           401M   42M  360M  11% /run
/dev/xvda1       15G   15G   20K 100% /
modules         100M   55M   46M  55% /lib/modules
tmpfs          1002M     0 1002M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs          1002M     0 1002M   0% /sys/fs/cgroup
tmpfs           201M     0  201M   0% /run/user/0
```
The problem lies on the fact that the script to update the website is not deleting the tmp folder. so /tmp is full

**Comment by anadahz** [comment]
This happen here: https://github.com/PrivacyLx/devops/blob/c70ff8c66b1b66763f8f11c83e92a3b63dc766b3/ansible/roles/caddy-website/templates/update-website.sh.j2#L34

Since we are using Ansible to manage the server it would be better to convert the (problematic) [script](https://github.com/PrivacyLx/devops/blob/c70ff8c66b1b66763f8f11c83e92a3b63dc766b3/ansible/roles/caddy-website/templates/update-website.sh.j2#L34) to Ansible tasks.

Both [caddy-website](https://github.com/PrivacyLx/devops/tree/master/ansible/roles/caddy-website) and [onion services](https://github.com/francisco-core/ansible-role-onion/tree/deb38b4f28c5f4ab03b39202439742c56c1ffb67) roles required more testing.

**Comment by francisco-core** [comment]
> This happen here: https://github.com/PrivacyLx/devops/blob/c70ff8c66b1b66763f8f11c83e92a3b63dc766b3/ansible/roles/caddy-website/templates/update-website.sh.j2#L34

Yeah. I think remove the tmp file there.



> Since we are using Ansible to manage the server it would be better to convert the (problematic) [script](https://github.com/PrivacyLx/devops/blob/c70ff8c66b1b66763f8f11c83e92a3b63dc766b3/ansible/roles/caddy-website/templates/update-website.sh.j2#L34) to Ansible tasks.

I thought about doing it in ansible, but I want it to run as a cron job and didn't find a way to run tasks in a cron job withouth the controller being always on

**Comment by anadahz** [comment]
> I thought about doing it in ansible, but I want it to run as a cron job and didn't find a way to run tasks in a cron job withouth the controller being always on

Have you checked the [cron module](https://docs.ansible.com/ansible/latest/modules/cron_module.html)?

**Comment by francisco-core** [comment]
Fixed here: https://github.com/PrivacyLx/devops/commit/5a93112fc60db1cc8e0f3264b4eab776bdec38c9
