### ISSUE TITLE
add community homepage

### ISSUE THREAD

**Issue by francisco-core** [PrivacyLx/privacylx-issue-tracker#41]
This will be directing people to:
  - forum - cafe.privacylx.org
  - matrix channel

**Comment by francisco-core** [comment]
Current status: 
![Screenshot-2019-8-27 Communities](https://user-images.githubusercontent.com/32313429/63776125-47828680-c8d0-11e9-995b-865a68ae6b83.png)

**Comment by anadahz** [comment]
@francisco-core: Looks great, thanks for working on it
Do you think that we should also add the git repositories there?

Edit: Perhaps we could add the IRC channel (with a webchat: https://irc.lc/oftc/privacylx/irc_lc_user_@@@) in case someone prefers IRC instead of Matrix (no need to create an account on IRC).

**Comment by francisco-core** [comment]
Yup. I just didn't know it at the time. Would this shorter version work: https://irc.lc/oftc/privacylx ?

**Comment by anadahz** [comment]
> Yup. I just didn't know it at the time. Would this shorter version work: https://irc.lc/oftc/privacylx ?

This will not work the syntax is:
`HTTP://IRC.LC/<NETWORK|SERVER>/<CHANNEL>/<Default_Nick_@@@>`

I think it's better to use OFTC's webchat as `irc.lc` seems to not currently work well (for the OFTC network). Please use this link: https://webchat.oftc.net/?channels=privacylx

**Comment by francisco-core** [comment]
> Do you think that we should also add the git repositories there?

Yup. I do. I've added that
