### ISSUE TITLE
Events should expire after the date

### ISSUE THREAD

**Issue by anadahz** [PrivacyLx/privacylx-issue-tracker#58]
Events on the website should expire right after the end of the event.
Currently an [old event](https://privacylx.org/events/inercia2019/) with `date: 2019-11-02T18:00:00` is active and displayed on the homepage.

**Comment by francisco-core** [comment]
@anadahz I think this has to do with the fact that with the introduction of https://github.com/PrivacyLx/devops/pull/10 the mechanism for updating the website from git changed.

Now it does ([check source](https://github.com/PrivacyLx/devops/blob/c0d1b09b3f25b8ebfec202d91e8ab2bdd22b0600/ansible/roles/website/templates/Caddyfile.j2#L13)) in the caddy config file:
```caddyfile
{% if caddy_git_interval %}
    interval {{ caddy_git_interval }}
{% endif %}
    repo {{ website_git }}
    args --recursive
    path {{ website_docker_webroot }}
    then hugo --destination={{ website_public }}
    }
```

And I'm guessing that this tries to pull the git repo but if it doesn't detect changes it doen't execute the `then command`.

I haven't tested this hypothesis yet.

---

### Temporary solution
Just redeploy the role

### Long-term solution
if the issue is in fact the one stated above, then we should add a cron job that redeploys the website. Or another solution.

**Comment by francisco-core** [comment]
Here's the previous code for the update job. It's the best so we might not use it:

https://github.com/PrivacyLx/devops/blob/5a93112fc60db1cc8e0f3264b4eab776bdec38c9/ansible/roles/caddy-website/tasks/build-website.yml#L104-L111
